#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

yabai -m config \
	window_origin_display default \
	window_placement second_child \
	insert_feedback_color 0xffd75f5f \
	split_ratio 0.50 \
	split_type auto \
	auto_balance off \
	top_padding 6 \
	bottom_padding 6 \
	left_padding 6 \
	right_padding 6 \
	window_gap 6 \
	layout bsp \
	mouse_modifier alt \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap

echo "yabai configuration loaded.."

# unmanaged apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^ExpressVPN$" manage=off
yabai -m rule --add app="^Toggl Track$" manage=off

echo "yabai rules loaded..."
