#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#

yabai -m config \
	mouse_follows_focus on \
	focus_follows_mouse off \
	window_origin_display default \
	window_placement second_child \
	window_opacity off \
	active_window_opacity 1.0 \
	normal_window_opacity 0.7 \
	insert_feedback_color 0xffd75f5f \
	split_ratio 0.50 \
	split_type auto \
	auto_balance off \
	top_padding 6 \
	bottom_padding 6 \
	left_padding 6 \
	right_padding 6 \
	window_gap 6 \
	layout bsp
# mouse_modifier ctrl+alt \
# mouse_action1 move \
# mouse_action2 resize \
# mouse_drop_action swap

echo "yabai configuration loaded.."

# unmanaged apps
yabai -m rule --add app="^(System Settings|1Password|ExpressVPN|FaceTime)$" manage=off

# Fix behavior where tiled (managed) windows appear below floating windows.
# See: https://github.com/koekeishiya/yabai/issues/1929#issuecomment-2003725298
yabai -m rule --add app=".*" sub-layer=normal

echo "yabai rules loaded..."
